name = "QuantumChaos"
uuid = "3c8cddf9-0b35-4818-b39a-cb173209c605"
version = "1.0.0-DEV"
authors = ["Kiize"]

[deps]
ArnoldiMethod = "ec485272-7323-5ecc-a04f-4719b315124d"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Kronecker = "2c470bb0-bcc8-11e8-3dad-c9649493f05e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
ArnoldiMethod = "0.4.0"
GLMakie = "0.13.6"
Kronecker = "0.5.5"
LinearAlgebra = "1.12.0"
ProgressMeter = "1.11.0"
SafeTestsets = "0.1.0"
SparseArrays = "1.12.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[targets]
test = ["Test", "SafeTestsets"]
